main/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import StringField, SubmitField, TextAreaField, FileField, RadioField
from wtforms import SelectField, HiddenField, BooleanField, PasswordField, DateTimeField, DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.validators import Required, ValidationError, Email, Length, Regexp, EqualTo


from ..models import *

from wtforms.validators import Required, ValidationError


choices=[('4:0','4:0'),
	('4:1','4:1'),
	('4:2','4:2'),
	('4:3','4:3'),
	('3:4','3:4'),
	('2:4','2:4'),
	('1:4','1:4'),
	('0:4','0:4')]

class PredictionForm(Form):

    answer = SelectField(u'Odgovor(i)', choices=choices,
    	coerce=unicode,validators=[Required()])
    submit = SubmitField(u'Unesi prognozu')


class SeriesForm(Form):

    home = StringField(u'Home',validators=[Required()])
    away = StringField(u'Away',validators=[Required()])

    submit = SubmitField(u'Unesi seriju')

class CloseForm(Form):


    submit = SubmitField(u'Zatvori predviđanja')


class CommentForm(Form):

    body = TextAreaField(u'Komentar',validators=[Required(), Length(1,200)])

    submit = SubmitField(u'Komentar')

main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

main/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-


from flask import Flask, render_template, session, redirect, url_for, flash, g, request, make_response, jsonify

from flask_wtf import Form
from wtforms import StringField, SubmitField, SelectMultipleField, TextAreaField, FileField, RadioField
from wtforms import SelectField, HiddenField, BooleanField, PasswordField, DateTimeField, DateField

from wtforms import widgets
from .. import db


from flask_login import login_required, login_user, logout_user, current_user
from . import main
from ..models import User, Series, Prediction, calculate_score, Comment
from .forms import PredictionForm,SeriesForm, CommentForm, CloseForm
from functools import wraps


def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user._get_current_object().is_admin:
            flash(u'Samo administrator!')

            return redirect(url_for('main.index'))
        return f(*args, **kwargs)
    return decorated_function



@main.route('/', methods=['GET','POST'])
def index():


    users = User.query.order_by(User.score.desc()).limit(7)
    # all open series
    open_series = Series.query.filter(Series.open==True).all()

    closed_series = Series.query.filter(Series.open==False).all()


    if current_user.is_authenticated:
        usr = current_user._get_current_object()



        form = CommentForm()

        if form.validate_on_submit():

            comment = Comment()
            comment.body = form.body.data
            comment.user = usr

            db.session.add(comment)


            msg = u'Dodat komentar.'
            flash(msg)


            return redirect(url_for('main.index'))

        comments = Comment.query.all()

    else:
        form = None
        comments = None

    return render_template('index.html', comments = comments,
        series = open_series, closed_series = closed_series, users = users, form = form)


@main.route('/predict/<id>', methods=['GET','POST'])
@login_required
def new_prediction(id):


    series = Series.query.get_or_404(id)

    usr = current_user._get_current_object()

    exists = Prediction.query.filter(
        Prediction.user==usr).filter(
        Prediction.series==series).first()

    if exists:
        preds = Prediction.query.filter(
            Prediction.series==series)

        return render_template('main/series.html',
            series = series, preds = preds)

    if not series.open:
        preds = Prediction.query.filter(
            Prediction.series==series)

        return render_template('main/series.html',
            series = series, preds = preds, not_open = True)

    if series.result:

        preds = Prediction.query.filter(
            Prediction.series==series)

        msg = u'Serija {0} - {1} je zatvorena, a izgleda da je nisi prognozirao :('.format(
            series.home, series.away)
        flash(msg)

        return render_template('main/series.html',
            series = series, preds = preds)

    form = PredictionForm()

    if form.validate_on_submit():

        prediction = Prediction()
        prediction.predicted = form.answer.data
        prediction.series = series
        prediction.user = usr

        db.session.add(prediction)


        msg = u'Prognozirao si seriju {0} - {1} da će da se završi rezultatom {2}'.format(
            series.home, series.away, prediction.predicted)
        flash(msg)


        return redirect(url_for('main.index'))


    return render_template('main/new_prediction.html', form = form, series = series)


@main.route('/series/new', methods=['GET','POST'])
@login_required
@admin_required
def new_series():


    form = SeriesForm()

    if form.validate_on_submit():

        series = Series()
        series.home = form.home.data
        series.away = form.away.data
        series.open = True

        db.session.add(series)


        msg = u'Uneta nova serija {0} - {1}'.format(
            series.home, series.away)
        flash(msg)


        return redirect(url_for('main.index'))


    return render_template('main/new_series.html', form = form)






@main.route('/close/<id>', methods=['GET','POST'])
@login_required
@admin_required
def close_series(id):


    series = Series.query.get_or_404(id)

    if series.open:
        msg = u'Serija {0} - {1} bi trebalo da je već zatvorena!'.format(
            series.home, series.away)
        flash(msg)

    if series.result:
        msg = u'Serija {0} - {1} je već zatvorena rezultatom {2}!'.format(
            series.home, series.away, series.result)
        flash(msg)
        return redirect(url_for('main.index'))


    form = PredictionForm()

    if form.validate_on_submit():

        series.result = form.answer.data
        series.open = False


        db.session.add(series)


        msg = u'Zaključio si seriju {0} - {1} rezultatom {2}'.format(
            series.home, series.away, series.result)
        flash(msg)

        # update the users scores
        predicts = Prediction.query.filter(Prediction.series==series).all()
        for pred in predicts:
            # get the score and update it
            user = pred.user
            score = calculate_score(pred.predicted, pred.series.result)
            user_score = user.score
            user.score = user_score+score
            print "Updated user {0}'s score by {1} for series {2}".format(
                user.username, score, pred.series)

            db.session.add(user)
            pred.score_made = calculate_score(pred.predicted, pred.series.result)
            db.session.add(pred)



        return redirect(url_for('main.index'))


    return render_template('main/close_series.html', form = form, series = series)


# no more predictions - series started

@main.route('/close-preds/<id>', methods=['GET','POST'])
@login_required
@admin_required
def close_preds_series(id):


    series = Series.query.get_or_404(id)

    # predictions for the series
    preds = Prediction.query.filter(Prediction.series==series).all()

    if series.open:
        msg = u'Serija {0} - {1} se zatvara za predviđanje!'.format(
            series.home, series.away)
        flash(msg)




    form = CloseForm()

    if form.validate_on_submit():

        series.open = False

        db.session.add(series)


        msg = u'Seriju {0} - {1} je zatvorena za predviđanja'.format(
            series.home, series.away)
        flash(msg)




        return redirect(url_for('main.index'))


    return render_template('main/close_pred_series.html', form = form, series = series, preds = preds)

@main.route('/user/<id>')
@login_required
def user_page(id):

    curr_usr = current_user._get_current_object()

    usr = User.query.get_or_404(id)

    if usr==curr_usr:
        return redirect(url_for('main.my_predictions'))

    #patients = Patient.query.filter(Patient.mother.has(phenoscore=10))

    preds= Prediction.query.filter(
        Prediction.user==usr).filter(Prediction.series.has(Series.open==False)).all()



    return render_template('main/user_page.html', preds=preds, user=usr)



@main.route('/predictions')
@login_required
def my_predictions():

    usr = current_user._get_current_object()


    preds= Prediction.query.filter(Prediction.user==usr).all()



    return render_template('main/my_preds.html', preds=preds)


@main.route('/scoreboard')
#@login_required
def scoreboard():


    #usr = current_user._get_current_object()

    users = User.query.order_by(User.score.desc()).all()

    return render_template('main/scoreboard.html', users = users)


@main.route('/help')
def help():


    return render_template('main/help.html')

@main.route('/close')
@login_required
@admin_required
def close_all_series():

    open_series = Series.query.filter(
        Series.open==True).all()



    return render_template('main/close_list.html',
        series = open_series)

templates/main/close_all.html
{% extends "base.html" %}


{% block content %}
<div class="container">

<h3>Otvorene serije</h3>

<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      
      <th>Serija</th>
      <th>zatvori</th>
    </tr>
  </thead>
  <tbody>
  {% for ser in series %}
    <tr>
      
      <td>{{ series.home }} - {{ series.away }}</td>
      <td><a href="{{ url_for('main.close_series',id=series.id) }}"</strong></td>
     
    </tr>
    {% endfor %}
    
  </tbody>
</table>

<hr/>

<div class="ct-chart ct-perfect-fourth"></div>

</div>
{% endblock %}

{% block extra_js %}

{% endblock %}

templates/main/close_list.html
{% extends "base.html" %}


{% block content %}
<div class="container">

<h3>Otvorene serije</h3>

{% if series %}
<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      
      <th>Serija</th>
      <th>zatvori</th>
    </tr>
  </thead>
  <tbody>

  {% for ser in series %}
  
    <tr>
      
      <td>{{ ser.home }} - {{ ser.away }}</td>
      <td><a class="btn btn-warning btn-block" href="{{ url_for('main.close_series',id=ser.id) }}">zatvori!</a></td>
     
    </tr>
    {% endfor %}
    
  </tbody>
</table>
{% else %}
<p class="lead">Nema otvorenih serija</p>
{% endif %}

<hr/>

<div class="ct-chart ct-perfect-fourth"></div>

</div>
{% endblock %}

{% block extra_js %}

{% endblock %}

templates/main/close_pred_series.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}
<div class="container">
<div class="jumbotron">
<h3>{{ series.home }} - {{ series.away }}</h3>
<p>Zatvaranje serije za predviđanja!</p>
<h5>Predviđanja za ovu seriju da sada:</h5>

<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      
      <th>Igrač</th>
      <th>Prognoza</th>
 
     </tr>
  </thead>
  <tbody>
  {% for pred in preds %}
    <tr>
  
      <td>{{ pred.user.username }}</td>
      <td><strong>{{ pred.predicted }}</strong></td>
  
     
    </tr>
    {% endfor %}
    
  </tbody>
</table>




</div>

    {{ wtf.quick_form(form,extra_classes="form-horizontal",button_map={'submit':'warning btn-block'}) }}
	
</div>
{% endblock %}

templates/main/close_series.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}
<div class="container">
<div class="jumbotron">
<h3>{{ series.home }} - {{ series.away }}</h3>
<p>Ti si admin i unosiš konačan (i tačan) rezultat serije.</p>
<p>Nakon toga bi trebalo da se izračunaju poeni za sve koji su prognozirali ovu seriju.</p>
<p class="lead text-center">Proveri ovde: <a href="http://espn.go.com/nba/standings">ESPN standings</a></p>
</div>

    {{ wtf.quick_form(form,extra_classes="form-horizontal",button_map={'submit':'warning btn-block'}) }}
<br/>	
</div>
{% endblock %}

templates/main/ctask.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Flasky{% endblock %}

{% block page_content %}


<h4>Zadatak br {{ task.id }}</h4>
<p class="lead">{{ task.question }}</p>
 
{{ wtf.quick_form(form) }}
 
{% endblock %}

templates/main/help.html
{% extends "base.html" %}


{% block content %}

<h2 class="text-center">Kako ovo radi?</h2>
<hr/>


<h4>Unošenje serija - otvorene i zatvorene</h4>
  <p>Admini unose serije čim se sazna koje su tačno. Serije su tada <strong>otvorene</strong>. Ove serije je moguće prognozirati.</p>
  <p>U idealnom slučaju veče pre početka serije (pre prve utakmice) admini <strong>zatvaraju</strong> seriju, u smislu da više nije moguće prognozirati. Ko je upisao - upisao je.</p>
  <p>Spisak serija se nalazi na početnoj strani, otvoreni ili zatvoreni katanac... jasno je manje-više.</p>

 <hr/>
 <h4>Unošenje konačnog rezultata</h4>
 <p>Admin unosi konačan rezultat serije i sistem obračunava bodove.</p>
 <p>Proverite bodove i prijavite greške, ukoliko ih ima. Na strani <a href="{{ url_for('main.scoreboard') }}">Top Lista</a> se nalazi spisak svih učesnika.</p> <hr/>
 <h4>Komentari</h4>
 <p>Moguće je komentarisanje svega na prvoj strani. Ovde nema neke moderacije, warnova i slično. Ukoliko imate problema, javite mi u komentarima ili na forumu.</p>


  <h4>Obračunavanje poena</h4><p>
  Ovo smo pitali par puta već, ja sam po nekoj logici i sećanju stavio kako sam stavio:

  <p>za svaku seriju u kojoj je pogođen pobednik, dobija se <strong>15</strong> poena.<hr/>
Tačan rezultat serije donosi još <strong>10</strong> poena. Greška od jedne pobede (na primer bilo je 4:2, a prognozirao si 4:1) donosi još <strong>5</strong> poena, greška od 2 pobede donosi još <strong>2</strong> poena. <hr/>
Pobeda gostujuće ekipe (slabiji <em>seed</em>) donosi još <strong>1</strong> poen, pošto nema domaćeg terena u bablu.</p>
<hr/>
Promašen pobednik serije donosi <strong>0 (nula)</strong> poena.
<hr/>
  </p>

<h4>Pobednik</h4>
<p>Pobednik je zvanično najbolji poznavalac plejofa NBA lige 2020. godine :)</p>

{% endblock %}

templates/main/my_preds.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}
<div class="container">

<h3>{{ current_user.username }} prognoze</h3>
<div class="well huge">{{ current_user.score }} poena</div>

<hr/>
{% for pred in preds %}
<h4><a href="{{ url_for('main.new_prediction',id=pred.series.id) }}">{{ pred.series.home }} - {{ pred.series.away }}</a></h4>
{% if pred.series.result %}
<p class="lead">Rezultat je bio <strong>{{ pred.series.result }}</strong>, tvoja prognoza je bila 
<span class="label label-warning">{{ pred.predicted }}</span> - dobio si <span class="label label-warning">{{ pred.score_made }}</span> poena.
{% else %}
<p><strong>Čeka se konačni rezultat serije.</strong> Tvoja prognoza je bila {{ pred.predicted }}.
{% endif %}
<hr/>
{% endfor %}

</div>
{% endblock %}

templates/main/new_prediction.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}
<div class="container">
<div class="jumbotron">
<h3>{{ series.home }} - {{ series.away }}</h3>
<p>Možeš samo jednom da prognoziraš rezultat serije. Veče pre početka će serija biti zatvorena i nema više mogućnosti prognoziranja.</p>
<p>4:0 znači da prognoziraš da će {{ series.home }} pobediti sa 4:0, 2:4 znači da prognoziraš da će {{ series.away }} pobediti sa 4:2 itd.</p>
</div>
  <div class="col-md-4 col-md-offset-4">
    {{ wtf.quick_form(form,button_map={'submit':'warning btn-block'}) }}
  </div>
	
</div>
{% endblock %}

templates/main/new_series.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}

<div class="registration">
<h3>Unošenje nove serije</h3>
<p>Home - ekipa koja ima prednost (bolji <em>seed</em>)</p>



    {{ wtf.quick_form(form,extra_classes="form-horizontal",button_map={'submit':'warning btn-block'}) }}
</div>
{% endblock %}

templates/main/scoreboard.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}

<h3 class="text-center">Top lista</h3>

<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Igrač</th>
      <th>Poena</th>
    </tr>
  </thead>
  <tbody>
  {% for user in users %}
    <tr {% if loop.index<11 %} class=""{% endif %}>
      <th scope="row">{{ loop.index }}</th>
      <td><a href="{{ url_for('main.user_page', id=user.id) }}">{{ user.username }}</a></td>
      <td><strong>{{ user.score }}</strong></td>

    </tr>
    {% endfor %}

  </tbody>
</table>




{% endblock %}

{% block extra_js %}

{% endblock %}

templates/main/series.html
{% extends "base.html" %}



{% block content %}
<div class="container">
<div class="jumbotron">
<h3 class="text-center">{% if not series.open %}<i class="fa fa-lock" aria-hidden="true"></i>  {% endif %}{{ series.home }} - {{ series.away }}</h3>
{% if series.result %}<h3 class="text-center"><span class="label label-warning">{{ series.result }}</span></h3>{% endif %}
{% if not_open %}<h4 class="text-center">Serija je zatvorena!</h4>{% endif %}

{% if current_user.is_authenticated and current_user.is_admin and not series.result %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <a class="btn btn-warning btn-block" href="{{ url_for('main.close_series',id=series.id) }}">konačni rezultat + obračun</a>
      <hr/>
      {% if series.open %}
      <a class="btn btn-warning btn-block" href="{{ url_for('main.close_preds_series',id=series.id) }}">zatvori!</a>
      {% endif %}
  </div>
</div>


{% endif %}


</div>

<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      
      <th>Igrač</th>
      <th>Prognoza</th>
      <th>Poeni</th>
     </tr>
  </thead>
  <tbody>
  {% for pred in preds %}
    <tr>
  
      <td>{{ pred.user.username }}</td>
      <td><strong>{{ pred.predicted }}</strong></td>
      <td><strong>{% if pred.series.result %}{{ pred.score_made }}{% else %}čeka se rezultat{% endif %}</strong></td>
     
    </tr>
    {% endfor %}
    
  </tbody>
</table>

	
</div>
{% endblock %}

templates/main/user_page.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}


{% block content %}
<div class="container">

<h3>{{ user.username }} prognoze</h3>
<div class="well huge">{{ user.total }} poena</div>

<hr/>

<table class="table table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Serija</th>
      <th>Prognoza</th>
      <th>Rezultat</th>
      <th>Poeni</th>
    </tr>
  </thead>
  <tbody>
  {% for pred in preds %}
    <tr>
      <th scope="row">{{ loop.index }}</th>
      <td><a href="{{ url_for('main.new_prediction',id=pred.series.id) }}">{{ pred.series.home }} - {{ pred.series.away }}</a></td>
      <td><strong>{{ pred.predicted }}</strong></td>
      <td><strong>{% if pred.series.result %}{{ pred.series.result }}{% else %}čeka se rezultat{% endif %}</strong></td>
      <td><strong>{{ pred.score_made }}</strong></td>
     	
    </tr>
    {% endfor %}
    
  </tbody>
</table>





</div>
{% endblock %}